#!/usr/bin/env bash
set -e

# initialize message colors
red=$'\e[31m'
green=$'\e[32m'
yellow=$'\e[33m'
end=$'\e[0m'

# install base libraries
echo "${red}Installing base libraries${end}"
sudo apt-get update && sudo apt-get install -y \
curl \
wget \
unzip \
cmake \
make \
libeigen3-dev \
libgoogle-glog-dev \
libboost-dev \
libyaml-cpp-dev \
libopencv-dev \
libgtest-dev

# build gtest
echo "${red}Building GTest${end}"
cd /usr/src/gtest
sudo cmake CMakeLists.txt
sudo make
sudo cp *.a /usr/lib

# setup ROS keys and install
echo "${red}Setting up ROS Keys${end}"
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
sudo apt-get update 

# Install ROS
echo "${red}Installing ROS Melodic${end}"
sudo apt-get install -f -y \
python-catkin-pkg-modules \
python-rosdistro-modules \
python-rospkg-modules \
ros-melodic-desktop \
python-rosdep \
python-rosinstall \
python-rosinstall-generator \
python-wstool \
ros-melodic-hector-* \
ros-melodic-velodyne

sudo rosdep init
rosdep update

echo "${green}Environment Build Successful!${end}"
