#!/usr/bin/env bash

# Exit on error. Append "|| true" if you expect an error.
set -o errexit
# Exit on error inside any functions or subshells.
set -o errtrace
# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
set -o nounset
# Catch the error in case mysqldump fails (but gzip succeeds) in `mysqldump |gzip`
set -o pipefail
# Turn on traces, useful while debugging but commented out by default
# set -o xtrace

sudo apt-get update
sudo apt-get install -y curl wget unzip cmake apt-utils git make cmake \
python-dev \
python-pip \
python3-dev \
python3-pip \
libeigen3-dev \
libgoogle-glog-dev \
libboost-dev \
libyaml-cpp-dev \
libopencv-dev

sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
sudo apt-get update 

# Installing ROS
sudo apt-get install -f -y \
python-catkin-pkg-modules \
python-rosdistro-modules \
python-rospkg-modules \
ros-melodic-desktop-full \
python-rosdep \
python-rosinstall \
python-rosinstall-generator \
python-wstool \
ros-melodic-hector-* \
ros-melodic-velodyne

sudo rosdep init
rosdep update

sudo apt-get install cmake libgtest-dev
cd /usr/src/gtest
sudo cmake CMakeLists.txt
sudo make
sudo cp *.a /usr/lib