LASER:
 JACKAL_LASER: 1
 JACKAL_LASER_HOKUYO: 1
 JACKAL_LASER_MOUNT: front
 JACKAL_LASER_TOPIC: front/scan
 JACKAL_LASER_OFFSET: 0.11 0 0
 JACKAL_LASER_RPY: 0 0 0

NAVSAT:
 JACKAL_NAVSAT: 1
 JACKAL_NAVSAT_MOUNT: rear
 JACKAL_NAVSAT_HEIGHT: 0.1

FENDER:
 JACKAL_FRONT_ACCESSORY_FENDER: 1
 JACKAL_FRONT_FENDER_UST10: 0
 JACKAL_REAR_ACCESSORY_FENDER: 1
 JACKAL_REAR_FENDER_UST10: 0
 JACKAL_ARK_ENCLOSURE: 0

FLEA3:
  JACKAL_FLEA3: 1
  JACKAL_FLEA3_MOUNT: front
  JACKAL_FLEA3_TILT: 0.0
  JACKAL_FLEA3_OFFSET: 0 0 0
  JACKAL_FLEA3_RPY: 0 0 0
  JACKAL_FLEA3_NAME: front

LIDAR:
  JACKAL_LIDAR: 1


